export const SET_SELECTED_INGREDIENT = 'SET_SELECTED_INGREDIENT';
export const UNSET_SELECTED_INGREDIENT = 'UNSET_SELECTED_INGREDIENT';
export const SET_ORDER_NUMBER = 'SET_ORDER_NUMBER';
export const OPEN_INGREDIENT_MODAL = 'OPEN_INGREDIENT_MODAL';
export const OPEN_ORDER_MODAL = 'OPEN_ORDER_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
// export const SELECT_BUN = 'SELECT_BUN';
