export const GET_COMPOSITION = 'GET_COMPOSITION';
export const SET_SELECTED_INGREDIENT = 'SET_SELECTED_INGREDIENT';
export const UNSET_SELECTED_INGREDIENT = 'UNSET_SELECTED_INGREDIENT';
export const SET_ORDER_NUMBER = 'SET_ORDER_NUMBER';
// export const SELECT_BUN = 'SELECT_BUN';
